prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Subscribed
    filters: is:open -author:@me repo:cli/cli repo:dlvhdr/gh-prs
    limit: 50 # optional limit per section
defaults:
  prsLimit: 20 # global limit
  preview:
    open: true
    width: 60
