working_directory = "None"

[bell]
animation = "EaseOutCirc"
color = "0x111111"
duration = 10

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#6272a4"
blue = "#d6acff"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#ffffff"
yellow = "#ffffa5"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#21222c"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
bright_foreground = "#ffffff"
foreground = "#f8f8f2"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.selection]
background = "#44475a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
style = "Underline"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = true
print_events = true
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "I"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "O"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "U"
mods = "Alt|Control"

[mouse]
hide_when_typing = true

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[scrolling]
history = 5000
multiplier = 3

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = false
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 40
lines = 40

[window.padding]
x = 4
y = 4
