#*
#*                  _    __ _ _
#*   __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#*  / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS:   https://github.com/goatfiles
#*  \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#*  |___/
#*          MAINTAINERS:
#*              AMTOINE: https://github.com/amtoine antoine#1306 7C5EE50BA27B86B7F9D5A7BA37AAE9B486CFF1AB
#*              ATXR:    https://github.com/atxr    atxr#6214    3B25AF716B608D41AB86C3D20E55E4B1DE5B2C8B
#*

theme = "onedark"

[editor]
line-number = "relative"
mouse = false
scrolloff	= 3
middle-click-paste = false
scroll-lines = 3
shell = ["nu", "-c"]
cursorline = false
gutters	= ["diagnostics", "line-numbers"]
auto-completion = true
auto-format = false
idle-timeout = 400
completion-trigger-len = 2
auto-info = true
true-color = false
rulers = []
color-modes = false
auto-pairs = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"
]
separator = "│"

[editor.lsp]
display-messages = false
auto-signature-help = true
display-signature-help-docs = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
parents	= true
ignore = true
git-ignore = true
git-global = true
git-exclude	= true

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = false
character = "│"

[keys.normal]
C-c = ":config-reload"
C-e = ":config-open"
C-r = ":reload"
